function emojiMap = sai_buildEmojiMap()
%SAI_BUILDEMOJIMAP  Build GoogLeNet label -> emoji lookup table.
%   All emoji are stored as HTML entity strings for reliable rendering
%   in MATLAB uilabel with Interpreter='html'.
    emojiKeys = { ...
        'golden retriever','Labrador retriever','German shepherd', ...
        'pug','beagle','French bulldog','Chihuahua','dalmatian', ...
        'collie','Rottweiler','boxer','cocker spaniel','poodle','husky', ...
        'tabby','Persian cat','Siamese cat','Egyptian cat','tiger cat', ...
        'teddy','teddy bear','rubber eraser','banana','orange','lemon', ...
        'pineapple','strawberry','fig','apple','Granny Smith', ...
        'pomegranate','jackfruit','cup','coffee mug','water bottle', ...
        'pop bottle','wine bottle','beer glass','tennis ball', ...
        'soccer ball','baseball','basketball','volleyball', ...
        'ping-pong ball','golf ball','rugby ball','sunglasses', ...
        'sunglass','cowboy hat','sombrero','bow tie','swimming trunks', ...
        'bikini','running shoe','sandal','clog','backpack', ...
        'pencil box','notebook','binder','pencil sharpener','ruler', ...
        'ballpoint','fountain pen','quill','spatula','frying pan', ...
        'wok','ladle','corkscrew','plate','bowl','tray','pitcher', ...
        'teapot','pot','acoustic guitar','electric guitar','drum', ...
        'drumstick','harmonica','maraca','saxophone','flute','violin', ...
        'banjo','umbrella','flashlight','remote control', ...
        'cellular telephone','digital clock','analog clock', ...
        'wall clock','alarm clock','shoe shop','running shoe','Loafer', ...
        'sandal','keyboard','mouse','laptop','monitor', ...
        'desktop computer','television','screen','iPod','headphone', ...
        'book','comic book','envelope','newspaper','hammer', ...
        'screwdriver','wrench','power drill','bicycle','mountain bike', ...
        'tricycle','scooter','skateboard','car','sports car', ...
        'convertible','jeep','truck','school bus','fire engine', ...
        'ambulance','police van','airplane','helicopter','rocket', ...
        'space shuttle','bird','robin','jay','magpie','flamingo', ...
        'goldfish','clownfish','starfish','jellyfish','sea urchin', ...
        'snail','butterfly','ladybug','bee','dragonfly','ant','frog', ...
        'tree frog','turtle','tortoise','snake','dinosaur', ...
        'brontosaurus','triceratops','mushroom','daisy','sunflower', ...
        'rose','pizza','cheeseburger','hot dog','pretzel','bagel', ...
        'ice cream','chocolate sauce','guacamole','burrito','taco', ...
        'donut','cupcake','birthday cake','ice lolly','cookie', ...
        'balloon','confetti','pinwheel','kite','toy','toyshop', ...
        'jigsaw puzzle','Rubik''s cube','Lego','abacus','top','crown', ...
        'necklace','ring','jewel','tiara','mask','globe','compass', ...
        'magnifying glass','binoculars','telescope','candle','torch', ...
        'lantern','lighthouse','church','castle','palace','fountain', ...
        'bridge','dam','lion','tiger','leopard','cheetah','cougar', ...
        'lynx','bear','panda','polar bear','koala','sloth','elephant', ...
        'giraffe','zebra','hippopotamus','rhinoceros','gorilla', ...
        'chimpanzee','orangutan','monkey','baboon','rabbit','hamster', ...
        'guinea pig','mouse','squirrel','penguin','ostrich','peacock', ...
        'toucan','parrot','owl','eagle','hawk','whale','dolphin', ...
        'seal','otter','walrus','spider','scorpion','crab','lobster', ...
        'octopus','squid','cowboy boot','stetson','mitten','glove', ...
        'sock','bucket','shovel','wheelbarrow','lawnmower','chainsaw', ...
        'traffic light','stop sign','mailbox','parking meter','bench', ...
        'piano','organ','harp','accordion','trombone','trumpet','tuba'};

    emojiVals = { ...
        '&#x1F415;','&#x1F415;','&#x1F415;', ...    % golden/lab/german shepherd
        '&#x1F436;','&#x1F436;','&#x1F436;','&#x1F436;','&#x1F436;', ... % pug-dalmatian
        '&#x1F436;','&#x1F436;','&#x1F436;','&#x1F436;','&#x1F436;','&#x1F436;', ... % collie-husky
        '&#x1F431;','&#x1F431;','&#x1F431;','&#x1F431;','&#x1F431;', ... % cats
        '&#x1F9F8;','&#x1F9F8;', ...                 % teddy
        '&#x270F;', ...                                % eraser
        '&#x1F34C;','&#x1F34A;','&#x1F34B;', ...     % banana/orange/lemon
        '&#x1F34D;','&#x1F353;','&#x1F347;','&#x1F34E;','&#x1F34F;', ... % pineapple-granny
        '&#x1F34E;','&#x1F348;', ...                  % pomegranate/jackfruit
        '&#x2615;','&#x2615;','&#x1F9F4;', ...       % cup/mug/water bottle
        '&#x1F37E;','&#x1F377;','&#x1F37A;', ...     % pop/wine/beer
        '&#x1F3BE;','&#x26BD;','&#x26BE;','&#x1F3C0;','&#x1F3D0;', ... % tennis-volleyball
        '&#x1F3D3;','&#x26F3;','&#x1F3C9;', ...      % ping-pong/golf/rugby
        '&#x1F576;','&#x1F576;', ...                  % sunglasses
        '&#x1F920;','&#x1F452;', ...                  % cowboy hat/sombrero
        '&#x1F380;','&#x1FA73;','&#x1F459;', ...     % bow tie/trunks/bikini
        '&#x1F45F;','&#x1FA74;','&#x1F45E;', ...     % running shoe/sandal/clog
        '&#x1F392;', ...                               % backpack
        '&#x270F;','&#x1F4D3;','&#x1F4D2;','&#x270F;','&#x1F4CF;', ... % pencil box-ruler
        '&#x1F58A;','&#x1F58B;','&#x1FAB6;', ...     % ballpoint/fountain/quill
        '&#x1F373;','&#x1F373;','&#x1F958;','&#x1F944;', ... % spatula-ladle
        '&#x1F37E;','&#x1F37D;','&#x1F963;','&#x1F37D;', ... % corkscrew-tray
        '&#x1FAD7;','&#x1FAD6;','&#x1F372;', ...     % pitcher/teapot/pot
        '&#x1F3B8;','&#x1F3B8;', ...                  % guitars
        '&#x1F941;','&#x1F941;', ...                  % drum/drumstick
        '&#x1F3B5;','&#x1F3B5;','&#x1F3B7;','&#x1F3B5;','&#x1F3BB;','&#x1FA95;', ... % harmonica-banjo
        '&#x2602;','&#x1F526;','&#x1F4FA;', ...      % umbrella/flashlight/remote
        '&#x1F4F1;', ...                               % cellular telephone
        '&#x1F550;','&#x1F550;','&#x1F550;','&#x23F0;', ... % clocks
        '&#x1F45F;','&#x1F45F;','&#x1F45E;','&#x1FA74;', ... % shoe shop-sandal
        '&#x2328;','&#x1F5B1;','&#x1F4BB;','&#x1F5A5;', ... % keyboard-monitor
        '&#x1F5A5;','&#x1F4FA;','&#x1F4FA;', ...     % desktop/tv/screen
        '&#x1F3B5;','&#x1F3A7;', ...                  % iPod/headphone
        '&#x1F4D6;','&#x1F4D6;','&#x2709;','&#x1F4F0;', ... % book-newspaper
        '&#x1F528;','&#x1FA9B;','&#x1F527;','&#x1F527;', ... % hammer-drill
        '&#x1F6B2;','&#x1F6B2;','&#x1F6B2;','&#x1F6F4;','&#x1F6F9;', ... % bikes-skateboard
        '&#x1F697;','&#x1F697;','&#x1F697;','&#x1F699;', ... % cars
        '&#x1F69A;','&#x1F68C;','&#x1F692;','&#x1F691;','&#x1F694;', ... % truck-police
        '&#x2708;','&#x1F681;','&#x1F680;','&#x1F680;', ... % airplane-shuttle
        '&#x1F426;','&#x1F426;','&#x1F426;','&#x1F426;','&#x1F9A9;', ... % birds
        '&#x1F41F;','&#x1F420;','&#x2B50;','&#x1FAB8;','&#x1F994;', ... % fish-urchin
        '&#x1F40C;','&#x1F98B;','&#x1F41E;','&#x1F41D;','&#x1F9A0;','&#x1F41C;', ... % snail-ant
        '&#x1F438;','&#x1F438;', ...                  % frogs
        '&#x1F422;','&#x1F422;','&#x1F40D;', ...     % turtle/tortoise/snake
        '&#x1F995;','&#x1F995;','&#x1F995;', ...     % dinosaurs
        '&#x1F344;','&#x1F33C;','&#x1F33B;','&#x1F339;', ... % mushroom-rose
        '&#x1F355;','&#x1F354;','&#x1F32D;','&#x1F968;','&#x1F96F;', ... % pizza-bagel
        '&#x1F366;','&#x1F36B;','&#x1F951;','&#x1F32F;','&#x1F32E;', ... % ice cream-taco
        '&#x1F369;','&#x1F9C1;','&#x1F382;','&#x1F36D;','&#x1F36A;', ... % donut-cookie
        '&#x1F388;','&#x1F389;','&#x1FA81;','&#x1FA81;', ... % balloon-kite
        '&#x1F9F8;','&#x1F9F8;', ...                  % toy/toyshop
        '&#x1F9E9;','&#x1F7E5;','&#x1F9F1;','&#x1F9EE;','&#x1FA80;', ... % puzzle-top
        '&#x1F451;','&#x1F4FF;','&#x1F48D;','&#x1F48E;','&#x1F451;', ... % crown-tiara
        '&#x1F3AD;','&#x1F30D;','&#x1F9ED;', ...     % mask/globe/compass
        '&#x1F50D;','&#x1F52D;','&#x1F52D;', ...     % magnifying-telescope
        '&#x1F56F;','&#x1F525;','&#x1F3EE;','&#x1F3E0;', ... % candle-lighthouse
        '&#x26EA;','&#x1F3F0;','&#x1F3F0;', ...      % church/castle/palace
        '&#x26F2;','&#x1F309;','&#x1F30A;', ...      % fountain/bridge/dam
        '&#x1F981;','&#x1F405;','&#x1F406;','&#x1F406;','&#x1F406;','&#x1F406;', ... % lion-lynx
        '&#x1F43B;','&#x1F43C;','&#x1F43B;&#x200D;&#x2744;','&#x1F428;','&#x1F9A5;', ... % bear-sloth
        '&#x1F418;','&#x1F992;','&#x1F993;','&#x1F99B;','&#x1F98F;', ... % elephant-rhino
        '&#x1F98D;','&#x1F412;','&#x1F9A7;','&#x1F412;','&#x1F412;', ... % gorilla-baboon
        '&#x1F430;','&#x1F439;','&#x1F439;','&#x1F42D;','&#x1F43F;', ... % rabbit-squirrel
        '&#x1F427;','&#x1F426;','&#x1F99A;','&#x1F426;','&#x1F99C;', ... % penguin-parrot
        '&#x1F989;','&#x1F985;','&#x1F985;', ...     % owl/eagle/hawk
        '&#x1F40B;','&#x1F42C;','&#x1F9AD;','&#x1F9A6;','&#x1F9AD;', ... % whale-walrus
        '&#x1F577;','&#x1F982;','&#x1F980;','&#x1F99E;', ... % spider-lobster
        '&#x1F419;','&#x1F991;', ...                  % octopus/squid
        '&#x1F920;','&#x1F920;', ...                  % cowboy boot/stetson
        '&#x1F9E4;','&#x1F9E4;','&#x1F9E6;', ...    % mitten/glove/sock
        '&#x1FAA3;','&#x26CF;','&#x1F6D2;','&#x1F33F;','&#x1FA9A;', ... % bucket-chainsaw
        '&#x1F6A6;','&#x1F6D1;','&#x1F4EE;','&#x1F17F;','&#x1FA91;', ... % traffic-bench
        '&#x1F3B9;','&#x1F3B9;','&#x1F3B5;','&#x1FA97;', ... % piano/organ/harp/accordion
        '&#x1F3BA;','&#x1F3BA;','&#x1F3BA;'};        % trombone/trumpet/tuba

    emojiMap = containers.Map(lower(emojiKeys), emojiVals);
end
