function emojiMap = sai_buildEmojiMap()
%SAI_BUILDEMOJIMAP  Build ImageNet label -> emoji lookup table.
%   All emoji are stored as HTML entity strings for reliable rendering
%   in MATLAB uilabel with Interpreter='html'.
%
%   Keys use the MODERNIZED label names (output of sai_modernizeLabel),
%   plus original ImageNet names as fallbacks.

    persistent cachedMap
    if ~isempty(cachedMap)
        emojiMap = cachedMap;
        return;
    end

    % Each row: { 'label', '&#xHEX;' }
    entries = { ...
        ... % === Dogs ===
        'golden retriever',   '&#x1F415;'; ...
        'Labrador retriever', '&#x1F415;'; ...
        'German shepherd',    '&#x1F415;'; ...
        'Labrador',           '&#x1F415;'; ...
        'Golden Retriever',   '&#x1F415;'; ...
        'German Shepherd',    '&#x1F415;'; ...
        'pug',                '&#x1F436;'; ...
        'beagle',             '&#x1F436;'; ...
        'French bulldog',     '&#x1F436;'; ...
        'Bulldog',            '&#x1F436;'; ...
        'Chihuahua',          '&#x1F436;'; ...
        'dalmatian',          '&#x1F436;'; ...
        'Dalmatian',          '&#x1F436;'; ...
        'collie',             '&#x1F436;'; ...
        'Collie',             '&#x1F436;'; ...
        'Rottweiler',         '&#x1F436;'; ...
        'boxer',              '&#x1F436;'; ...
        'cocker spaniel',     '&#x1F436;'; ...
        'poodle',             '&#x1F436;'; ...
        'Poodle',             '&#x1F436;'; ...
        'husky',              '&#x1F436;'; ...
        'Husky',              '&#x1F436;'; ...
        'Corgi',              '&#x1F436;'; ...
        'Yorkie',             '&#x1F436;'; ...
        'Boston Terrier',     '&#x1F436;'; ...
        'Sheepdog',           '&#x1F436;'; ...
        'Dog',                '&#x1F436;'; ...
        ... % === Cats ===
        'tabby',              '&#x1F431;'; ...
        'Persian cat',        '&#x1F431;'; ...
        'Siamese cat',        '&#x1F431;'; ...
        'Egyptian cat',       '&#x1F431;'; ...
        'tiger cat',          '&#x1F431;'; ...
        'Cat',                '&#x1F431;'; ...
        ... % === Wild cats ===
        'lion',               '&#x1F981;'; ...
        'tiger',              '&#x1F405;'; ...
        'leopard',            '&#x1F406;'; ...
        'cheetah',            '&#x1F406;'; ...
        'cougar',             '&#x1F406;'; ...
        'Mountain Lion',      '&#x1F406;'; ...
        'lynx',               '&#x1F406;'; ...
        'Snow Leopard',       '&#x1F406;'; ...
        'snow leopard',       '&#x1F406;'; ...
        'jaguar',             '&#x1F406;'; ...
        ... % === Wild canines ===
        'Wolf',               '&#x1F43A;'; ...
        'timber wolf',        '&#x1F43A;'; ...
        'white wolf',         '&#x1F43A;'; ...
        'red wolf',           '&#x1F43A;'; ...
        'coyote',             '&#x1F43A;'; ...
        'dingo',              '&#x1F43A;'; ...
        'Wild Dog',           '&#x1F43A;'; ...
        'hyena',              '&#x1F43A;'; ...
        'Fox',                '&#x1F98A;'; ...
        'red fox',            '&#x1F98A;'; ...
        'kit fox',            '&#x1F98A;'; ...
        'Arctic Fox',         '&#x1F98A;'; ...
        'Arctic fox',         '&#x1F98A;'; ...
        'grey fox',           '&#x1F98A;'; ...
        ... % === Bears ===
        'bear',               '&#x1F43B;'; ...
        'Bear',               '&#x1F43B;'; ...
        'brown bear',         '&#x1F43B;'; ...
        'Black Bear',         '&#x1F43B;'; ...
        'American black bear','&#x1F43B;'; ...
        'sloth bear',         '&#x1F43B;'; ...
        'panda',              '&#x1F43C;'; ...
        'Panda',              '&#x1F43C;'; ...
        'giant panda',        '&#x1F43C;'; ...
        'Polar Bear',         '&#x1F43B;&#x200D;&#x2744;'; ...
        'polar bear',         '&#x1F43B;&#x200D;&#x2744;'; ...
        'ice bear',           '&#x1F43B;&#x200D;&#x2744;'; ...
        'koala',              '&#x1F428;'; ...
        'Sloth',              '&#x1F9A5;'; ...
        'sloth',              '&#x1F9A5;'; ...
        'three-toed sloth',   '&#x1F9A5;'; ...
        ... % === Primates ===
        'gorilla',            '&#x1F98D;'; ...
        'chimpanzee',         '&#x1F412;'; ...
        'orangutan',          '&#x1F9A7;'; ...
        'Monkey',             '&#x1F412;'; ...
        'monkey',             '&#x1F412;'; ...
        'baboon',             '&#x1F412;'; ...
        'Lemur',              '&#x1F412;'; ...
        ... % === Other mammals ===
        'Elephant',           '&#x1F418;'; ...
        'elephant',           '&#x1F418;'; ...
        'Indian elephant',    '&#x1F418;'; ...
        'African elephant',   '&#x1F418;'; ...
        'tusker',             '&#x1F418;'; ...
        'Red Panda',          '&#x1F9A8;'; ...
        'lesser panda',       '&#x1F9A8;'; ...
        'giraffe',            '&#x1F992;'; ...
        'zebra',              '&#x1F993;'; ...
        'hippopotamus',       '&#x1F99B;'; ...
        'rhinoceros',         '&#x1F98F;'; ...
        'rabbit',             '&#x1F430;'; ...
        'Rabbit',             '&#x1F430;'; ...
        'wood rabbit',        '&#x1F430;'; ...
        'hare',               '&#x1F430;'; ...
        'Angora',             '&#x1F430;'; ...
        'hamster',            '&#x1F439;'; ...
        'guinea pig',         '&#x1F439;'; ...
        'Guinea Pig',         '&#x1F439;'; ...
        'squirrel',           '&#x1F43F;'; ...
        'Squirrel',           '&#x1F43F;'; ...
        'fox squirrel',       '&#x1F43F;'; ...
        'Groundhog',          '&#x1F43F;'; ...
        'marmot',             '&#x1F43F;'; ...
        'beaver',             '&#x1F9AB;'; ...
        'Pig',                '&#x1F437;'; ...
        'hog',                '&#x1F437;'; ...
        'wild boar',          '&#x1F417;'; ...
        'Wild Pig',           '&#x1F417;'; ...
        'warthog',            '&#x1F417;'; ...
        'Horse',              '&#x1F434;'; ...
        'sorrel',             '&#x1F434;'; ...
        'ox',                 '&#x1F404;'; ...
        'Buffalo',            '&#x1F403;'; ...
        'water buffalo',      '&#x1F403;'; ...
        'bison',              '&#x1F403;'; ...
        'Sheep',              '&#x1F411;'; ...
        'ram',                '&#x1F411;'; ...
        'bighorn',            '&#x1F411;'; ...
        'Mountain Goat',      '&#x1F410;'; ...
        'ibex',               '&#x1F410;'; ...
        'Antelope',           '&#x1F98C;'; ...
        'hartebeest',         '&#x1F98C;'; ...
        'impala',             '&#x1F98C;'; ...
        'gazelle',            '&#x1F98C;'; ...
        'Camel',              '&#x1F42B;'; ...
        'Arabian camel',      '&#x1F42B;'; ...
        'llama',              '&#x1F999;'; ...
        'skunk',              '&#x1F9A8;'; ...
        'badger',             '&#x1F9A1;'; ...
        'otter',              '&#x1F9A6;'; ...
        'Weasel',             '&#x1F9A6;'; ...
        'Ferret',             '&#x1F9A6;'; ...
        'armadillo',          '&#x1F9A6;'; ...
        'Wallaby',            '&#x1F998;'; ...
        'wallaby',            '&#x1F998;'; ...
        'meerkat',            '&#x1F9A6;'; ...
        'mongoose',           '&#x1F9A6;'; ...
        ... % === Marine mammals ===
        'Whale',              '&#x1F40B;'; ...
        'whale',              '&#x1F40B;'; ...
        'grey whale',         '&#x1F40B;'; ...
        'Orca',               '&#x1F40B;'; ...
        'killer whale',       '&#x1F40B;'; ...
        'dolphin',            '&#x1F42C;'; ...
        'sea lion',           '&#x1F9AD;'; ...
        'seal',               '&#x1F9AD;'; ...
        'Manatee',            '&#x1F9AD;'; ...
        'dugong',             '&#x1F9AD;'; ...
        'walrus',             '&#x1F9AD;'; ...
        ... % === Birds ===
        'bird',               '&#x1F426;'; ...
        'Bird',               '&#x1F426;'; ...
        'robin',              '&#x1F426;'; ...
        'jay',                '&#x1F426;'; ...
        'magpie',             '&#x1F426;'; ...
        'flamingo',           '&#x1F9A9;'; ...
        'Rooster',            '&#x1F413;'; ...
        'cock',               '&#x1F413;'; ...
        'Chicken',            '&#x1F414;'; ...
        'hen',                '&#x1F414;'; ...
        'ostrich',            '&#x1F426;'; ...
        'Duck',               '&#x1F986;'; ...
        'drake',              '&#x1F986;'; ...
        'goose',              '&#x1F986;'; ...
        'Swan',               '&#x1F9A2;'; ...
        'black swan',         '&#x1F9A2;'; ...
        'peacock',            '&#x1F99A;'; ...
        'Penguin',            '&#x1F427;'; ...
        'penguin',            '&#x1F427;'; ...
        'king penguin',       '&#x1F427;'; ...
        'toucan',             '&#x1F426;'; ...
        'Parrot',             '&#x1F99C;'; ...
        'parrot',             '&#x1F99C;'; ...
        'macaw',              '&#x1F99C;'; ...
        'African grey',       '&#x1F99C;'; ...
        'lorikeet',           '&#x1F99C;'; ...
        'Cockatoo',           '&#x1F99C;'; ...
        'sulphur-crested cockatoo', '&#x1F99C;'; ...
        'owl',                '&#x1F989;'; ...
        'Owl',                '&#x1F989;'; ...
        'great grey owl',     '&#x1F989;'; ...
        'Eagle',              '&#x1F985;'; ...
        'eagle',              '&#x1F985;'; ...
        'bald eagle',         '&#x1F985;'; ...
        'hawk',               '&#x1F985;'; ...
        'vulture',            '&#x1F985;'; ...
        'hummingbird',        '&#x1F426;'; ...
        'hornbill',           '&#x1F426;'; ...
        'Stork',              '&#x1F426;'; ...
        'pelican',            '&#x1F426;'; ...
        'Heron',              '&#x1F426;'; ...
        'crane',              '&#x1F426;'; ...
        'albatross',          '&#x1F426;'; ...
        'quail',              '&#x1F426;'; ...
        'partridge',          '&#x1F426;'; ...
        'spoonbill',          '&#x1F426;'; ...
        ... % === Fish ===
        'goldfish',           '&#x1F41F;'; ...
        'Fish',               '&#x1F41F;'; ...
        'tench',              '&#x1F41F;'; ...
        'coho',               '&#x1F41F;'; ...
        'sturgeon',           '&#x1F41F;'; ...
        'gar',                '&#x1F41F;'; ...
        'barracouta',         '&#x1F41F;'; ...
        'Clownfish',          '&#x1F420;'; ...
        'anemone fish',       '&#x1F420;'; ...
        'Pufferfish',         '&#x1F421;'; ...
        'puffer',             '&#x1F421;'; ...
        'lionfish',           '&#x1F41F;'; ...
        'eel',                '&#x1F41F;'; ...
        'Shark',              '&#x1F988;'; ...
        'great white shark',  '&#x1F988;'; ...
        'tiger shark',        '&#x1F988;'; ...
        'hammerhead',         '&#x1F988;'; ...
        'Ray',                '&#x1F41F;'; ...
        'electric ray',       '&#x1F41F;'; ...
        'stingray',           '&#x1F41F;'; ...
        ... % === Reptiles ===
        'Snake',              '&#x1F40D;'; ...
        'snake',              '&#x1F40D;'; ...
        'boa constrictor',    '&#x1F40D;'; ...
        'Turtle',             '&#x1F422;'; ...
        'turtle',             '&#x1F422;'; ...
        'tortoise',           '&#x1F422;'; ...
        'Sea Turtle',         '&#x1F422;'; ...
        'loggerhead',         '&#x1F422;'; ...
        'leatherback turtle', '&#x1F422;'; ...
        'mud turtle',         '&#x1F422;'; ...
        'terrapin',           '&#x1F422;'; ...
        'box turtle',         '&#x1F422;'; ...
        'Crocodile',          '&#x1F40A;'; ...
        'African crocodile',  '&#x1F40A;'; ...
        'Alligator',          '&#x1F40A;'; ...
        'American alligator', '&#x1F40A;'; ...
        'Lizard',             '&#x1F98E;'; ...
        'Iguana',             '&#x1F98E;'; ...
        'common iguana',      '&#x1F98E;'; ...
        'Chameleon',          '&#x1F98E;'; ...
        'American chameleon',  '&#x1F98E;'; ...
        'African chameleon',  '&#x1F98E;'; ...
        'Gecko',              '&#x1F98E;'; ...
        'banded gecko',       '&#x1F98E;'; ...
        'Komodo dragon',      '&#x1F98E;'; ...
        'triceratops',        '&#x1F995;'; ...
        'dinosaur',           '&#x1F995;'; ...
        'brontosaurus',       '&#x1F995;'; ...
        ... % === Amphibians ===
        'frog',               '&#x1F438;'; ...
        'Frog',               '&#x1F438;'; ...
        'tree frog',          '&#x1F438;'; ...
        'bullfrog',           '&#x1F438;'; ...
        'Salamander',         '&#x1F98E;'; ...
        'Newt',               '&#x1F98E;'; ...
        'axolotl',            '&#x1F98E;'; ...
        ... % === Insects ===
        'butterfly',          '&#x1F98B;'; ...
        'Butterfly',          '&#x1F98B;'; ...
        'monarch',            '&#x1F98B;'; ...
        'admiral',            '&#x1F98B;'; ...
        'cabbage butterfly',  '&#x1F98B;'; ...
        'sulphur butterfly',  '&#x1F98B;'; ...
        'lycaenid',           '&#x1F98B;'; ...
        'ringlet',            '&#x1F98B;'; ...
        'ladybug',            '&#x1F41E;'; ...
        'bee',                '&#x1F41D;'; ...
        'dragonfly',          '&#x1F9A0;'; ...
        'Dragonfly',          '&#x1F9A0;'; ...
        'damselfly',          '&#x1F9A0;'; ...
        'ant',                '&#x1F41C;'; ...
        'grasshopper',        '&#x1F997;'; ...
        'cricket',            '&#x1F997;'; ...
        'cockroach',          '&#x1FAB3;'; ...
        'Beetle',             '&#x1F41E;'; ...
        'Bug',                '&#x1F41C;'; ...
        'Stick Bug',          '&#x1F41C;'; ...
        'Praying Mantis',     '&#x1F41C;'; ...
        'mantis',             '&#x1F41C;'; ...
        'cicada',             '&#x1F41C;'; ...
        'fly',                '&#x1F41C;'; ...
        'scorpion',           '&#x1F982;'; ...
        ... % === Arachnids & small creatures ===
        'spider',             '&#x1F577;'; ...
        'Spider',             '&#x1F577;'; ...
        'tarantula',          '&#x1F577;'; ...
        'tick',               '&#x1F577;'; ...
        'centipede',          '&#x1F577;'; ...
        'snail',              '&#x1F40C;'; ...
        'slug',               '&#x1F40C;'; ...
        'Seashell',           '&#x1F41A;'; ...
        'conch',              '&#x1F41A;'; ...
        ... % === Marine invertebrates ===
        'starfish',           '&#x2B50;'; ...
        'jellyfish',          '&#x1FAB8;'; ...
        'sea urchin',         '&#x1F994;'; ...
        'Coral',              '&#x1FAB8;'; ...
        'brain coral',        '&#x1FAB8;'; ...
        'sea anemone',        '&#x1FAB8;'; ...
        'Nautilus',           '&#x1F41A;'; ...
        'chambered nautilus', '&#x1F41A;'; ...
        'Crab',               '&#x1F980;'; ...
        'crab',               '&#x1F980;'; ...
        'Dungeness crab',     '&#x1F980;'; ...
        'rock crab',          '&#x1F980;'; ...
        'fiddler crab',       '&#x1F980;'; ...
        'king crab',          '&#x1F980;'; ...
        'hermit crab',        '&#x1F980;'; ...
        'Lobster',            '&#x1F99E;'; ...
        'lobster',            '&#x1F99E;'; ...
        'American lobster',   '&#x1F99E;'; ...
        'spiny lobster',      '&#x1F99E;'; ...
        'crayfish',           '&#x1F99E;'; ...
        'octopus',            '&#x1F419;'; ...
        'squid',              '&#x1F991;'; ...
        ... % === Fruits ===
        'banana',             '&#x1F34C;'; ...
        'orange',             '&#x1F34A;'; ...
        'lemon',              '&#x1F34B;'; ...
        'pineapple',          '&#x1F34D;'; ...
        'strawberry',         '&#x1F353;'; ...
        'Apple',              '&#x1F34E;'; ...
        'apple',              '&#x1F34E;'; ...
        'Granny Smith',       '&#x1F34F;'; ...
        'fig',                '&#x1F347;'; ...
        'pomegranate',        '&#x1F34E;'; ...
        'jackfruit',          '&#x1F348;'; ...
        'Fruit',              '&#x1F34E;'; ...
        'custard apple',      '&#x1F34E;'; ...
        ... % === Vegetables ===
        'mushroom',           '&#x1F344;'; ...
        'broccoli',           '&#x1F966;'; ...
        'cauliflower',        '&#x1F966;'; ...
        'corn',               '&#x1F33D;'; ...
        'cucumber',           '&#x1F952;'; ...
        'zucchini',           '&#x1F952;'; ...
        'Squash',             '&#x1F952;'; ...
        'Pepper',             '&#x1FAD1;'; ...
        'bell pepper',        '&#x1FAD1;'; ...
        'artichoke',          '&#x1F952;'; ...
        'Cabbage',            '&#x1F96C;'; ...
        'head cabbage',       '&#x1F96C;'; ...
        ... % === Food ===
        'pizza',              '&#x1F355;'; ...
        'cheeseburger',       '&#x1F354;'; ...
        'hotdog',             '&#x1F32D;'; ...
        'hot dog',            '&#x1F32D;'; ...
        'pretzel',            '&#x1F968;'; ...
        'bagel',              '&#x1F96F;'; ...
        'ice cream',          '&#x1F366;'; ...
        'chocolate sauce',    '&#x1F36B;'; ...
        'guacamole',          '&#x1F951;'; ...
        'burrito',            '&#x1F32F;'; ...
        'taco',               '&#x1F32E;'; ...
        'donut',              '&#x1F369;'; ...
        'cupcake',            '&#x1F9C1;'; ...
        'birthday cake',      '&#x1F382;'; ...
        'Popsicle',           '&#x1F36D;'; ...
        'ice lolly',          '&#x1F36D;'; ...
        'cookie',             '&#x1F36A;'; ...
        'Bread',              '&#x1F35E;'; ...
        'French loaf',        '&#x1F35E;'; ...
        'Pasta',              '&#x1F35D;'; ...
        'carbonara',          '&#x1F35D;'; ...
        'spaghetti',          '&#x1F35D;'; ...
        'Meatloaf',           '&#x1F356;'; ...
        'meat loaf',          '&#x1F356;'; ...
        'Pot Pie',            '&#x1F967;'; ...
        'potpie',             '&#x1F967;'; ...
        'Mashed Potatoes',    '&#x1F954;'; ...
        'mashed potato',      '&#x1F954;'; ...
        'Soup',               '&#x1F35C;'; ...
        'consomme',           '&#x1F35C;'; ...
        'hot pot',            '&#x1F35C;'; ...
        'Dessert',            '&#x1F370;'; ...
        'trifle',             '&#x1F370;'; ...
        ... % === Drinks ===
        'Coffee',             '&#x2615;'; ...
        'espresso',           '&#x2615;'; ...
        'cup',                '&#x2615;'; ...
        'Mug',                '&#x2615;'; ...
        'coffee mug',         '&#x2615;'; ...
        'teapot',             '&#x1FAD6;'; ...
        'Water Bottle',       '&#x1F9F4;'; ...
        'water bottle',       '&#x1F9F4;'; ...
        'Soda Bottle',        '&#x1F37E;'; ...
        'pop bottle',         '&#x1F37E;'; ...
        'Wine',               '&#x1F377;'; ...
        'Wine Bottle',        '&#x1F377;'; ...
        'wine bottle',        '&#x1F377;'; ...
        'red wine',           '&#x1F377;'; ...
        'Beer Bottle',        '&#x1F37A;'; ...
        'beer bottle',        '&#x1F37A;'; ...
        'Beer Glass',         '&#x1F37A;'; ...
        'beer glass',         '&#x1F37A;'; ...
        'eggnog',             '&#x1F95B;'; ...
        ... % === Sports ===
        'tennis ball',        '&#x1F3BE;'; ...
        'soccer ball',        '&#x26BD;'; ...
        'baseball',           '&#x26BE;'; ...
        'basketball',         '&#x1F3C0;'; ...
        'volleyball',         '&#x1F3D0;'; ...
        'ping-pong ball',     '&#x1F3D3;'; ...
        'golf ball',          '&#x26F3;'; ...
        'rugby ball',         '&#x1F3C9;'; ...
        'Hockey Puck',        '&#x1F3D2;'; ...
        'puck',               '&#x1F3D2;'; ...
        'Tennis Racket',      '&#x1F3BE;'; ...
        'racket',             '&#x1F3BE;'; ...
        'croquet ball',       '&#x26F3;'; ...
        'pool table',         '&#x1F3B1;'; ...
        ... % === Clothing & accessories ===
        'sunglasses',         '&#x1F576;'; ...
        'Sunglasses',         '&#x1F576;'; ...
        'sunglass',           '&#x1F576;'; ...
        'cowboy hat',         '&#x1F920;'; ...
        'sombrero',           '&#x1F452;'; ...
        'bow tie',            '&#x1F380;'; ...
        'swimming trunks',    '&#x1FA73;'; ...
        'Swimsuit',           '&#x1FA73;'; ...
        'maillot',            '&#x1FA73;'; ...
        'bikini',             '&#x1F459;'; ...
        'Sneaker',            '&#x1F45F;'; ...
        'running shoe',       '&#x1F45F;'; ...
        'Shoe',               '&#x1F45E;'; ...
        'Loafer',             '&#x1F45E;'; ...
        'sandal',             '&#x1FA74;'; ...
        'clog',               '&#x1F45E;'; ...
        'Jeans',              '&#x1F456;'; ...
        'jean',               '&#x1F456;'; ...
        'Hoodie',             '&#x1F9E5;'; ...
        'sweatshirt',         '&#x1F9E5;'; ...
        'Sports Jersey',      '&#x1F455;'; ...
        'jersey',             '&#x1F455;'; ...
        'Pajamas',            '&#x1F455;'; ...
        'pajama',             '&#x1F455;'; ...
        'Kimono',             '&#x1F458;'; ...
        'kimono',             '&#x1F458;'; ...
        'Graduation Cap',     '&#x1F393;'; ...
        'mortarboard',        '&#x1F393;'; ...
        'Graduation Gown',    '&#x1F393;'; ...
        'academic gown',      '&#x1F393;'; ...
        'Helmet',             '&#x26D1;'; ...
        'crash helmet',       '&#x26D1;'; ...
        'football helmet',    '&#x26D1;'; ...
        'cowboy boot',        '&#x1F920;'; ...
        'stetson',            '&#x1F920;'; ...
        'mitten',             '&#x1F9E4;'; ...
        'glove',              '&#x1F9E4;'; ...
        'sock',               '&#x1F9E6;'; ...
        'Coat',               '&#x1F9E5;'; ...
        'fur coat',           '&#x1F9E5;'; ...
        'trench coat',        '&#x1F9E5;'; ...
        'Cape',               '&#x1F9E5;'; ...
        'cloak',              '&#x1F9E5;'; ...
        'Poncho',             '&#x1F9E5;'; ...
        'poncho',             '&#x1F9E5;'; ...
        'Hat',                '&#x1F452;'; ...
        'bonnet',             '&#x1F452;'; ...
        'Crown',              '&#x1F451;'; ...
        'crown',              '&#x1F451;'; ...
        'necklace',           '&#x1F4FF;'; ...
        'ring',               '&#x1F48D;'; ...
        'jewel',              '&#x1F48E;'; ...
        'tiara',              '&#x1F451;'; ...
        'lipstick',           '&#x1F484;'; ...
        'purse',              '&#x1F45C;'; ...
        'Purse',              '&#x1F45C;'; ...
        'backpack',           '&#x1F392;'; ...
        'Dress',              '&#x1F457;'; ...
        'gown',               '&#x1F457;'; ...
        'Skirt',              '&#x1F457;'; ...
        'miniskirt',          '&#x1F457;'; ...
        'sarong',             '&#x1F457;'; ...
        'Armor',              '&#x1F6E1;'; ...
        'chain mail',         '&#x1F6E1;'; ...
        'breastplate',        '&#x1F6E1;'; ...
        'Robe',               '&#x1F9E5;'; ...
        'abaya',              '&#x1F9E5;'; ...
        'Tie',                '&#x1F454;'; ...
        'Windsor tie',        '&#x1F454;'; ...
        'bolo tie',           '&#x1F454;'; ...
        ... % === Music ===
        'acoustic guitar',    '&#x1F3B8;'; ...
        'electric guitar',    '&#x1F3B8;'; ...
        'drum',               '&#x1F941;'; ...
        'drumstick',          '&#x1F941;'; ...
        'harmonica',          '&#x1F3B5;'; ...
        'maraca',             '&#x1F3B5;'; ...
        'Saxophone',          '&#x1F3B7;'; ...
        'saxophone',          '&#x1F3B7;'; ...
        'sax',                '&#x1F3B7;'; ...
        'flute',              '&#x1F3B5;'; ...
        'Flute',              '&#x1F3B5;'; ...
        'violin',             '&#x1F3BB;'; ...
        'banjo',              '&#x1FA95;'; ...
        'cello',              '&#x1F3BB;'; ...
        'Piano',              '&#x1F3B9;'; ...
        'piano',              '&#x1F3B9;'; ...
        'grand piano',        '&#x1F3B9;'; ...
        'upright',            '&#x1F3B9;'; ...
        'organ',              '&#x1F3B9;'; ...
        'harp',               '&#x1F3B5;'; ...
        'accordion',          '&#x1FA97;'; ...
        'Xylophone',          '&#x1F3B5;'; ...
        'marimba',            '&#x1F3B5;'; ...
        'Trumpet',            '&#x1F3BA;'; ...
        'trumpet',            '&#x1F3BA;'; ...
        'trombone',           '&#x1F3BA;'; ...
        'cornet',             '&#x1F3BA;'; ...
        'French horn',        '&#x1F4EF;'; ...
        'tuba',               '&#x1F3BA;'; ...
        ... % === School & office ===
        'Pencil Case',        '&#x270F;'; ...
        'pencil box',         '&#x270F;'; ...
        'Laptop',             '&#x1F4BB;'; ...
        'notebook',           '&#x1F4D3;'; ...
        'laptop',             '&#x1F4BB;'; ...
        'Binder',             '&#x1F4D2;'; ...
        'binder',             '&#x1F4D2;'; ...
        'pencil sharpener',   '&#x270F;'; ...
        'Ruler',              '&#x1F4CF;'; ...
        'ruler',              '&#x1F4CF;'; ...
        'rule',               '&#x1F4CF;'; ...
        'Pen',                '&#x1F58A;'; ...
        'ballpoint',          '&#x1F58A;'; ...
        'fountain pen',       '&#x1F58B;'; ...
        'quill',              '&#x1FAB6;'; ...
        'Eraser',             '&#x270F;'; ...
        'rubber eraser',      '&#x270F;'; ...
        'book',               '&#x1F4D6;'; ...
        'comic book',         '&#x1F4D6;'; ...
        'envelope',           '&#x2709;'; ...
        'newspaper',          '&#x1F4F0;'; ...
        ... % === Kitchen ===
        'spatula',            '&#x1F373;'; ...
        'frying pan',         '&#x1F373;'; ...
        'wok',                '&#x1F958;'; ...
        'ladle',              '&#x1F944;'; ...
        'corkscrew',          '&#x1F37E;'; ...
        'Plate',              '&#x1F37D;'; ...
        'plate',              '&#x1F37D;'; ...
        'Bowl',               '&#x1F963;'; ...
        'bowl',               '&#x1F963;'; ...
        'mixing bowl',        '&#x1F963;'; ...
        'soup bowl',          '&#x1F963;'; ...
        'tray',               '&#x1F37D;'; ...
        'Pitcher',            '&#x1FAD7;'; ...
        'pitcher',            '&#x1FAD7;'; ...
        'Teapot',             '&#x1FAD6;'; ...
        'teapot',             '&#x1FAD6;'; ...
        'pot',                '&#x1F372;'; ...
        'Cauldron',           '&#x1F372;'; ...
        'caldron',            '&#x1F372;'; ...
        'Slow Cooker',        '&#x1F372;'; ...
        'Crock Pot',          '&#x1F372;'; ...
        'Coffee Pot',         '&#x2615;'; ...
        'coffeepot',          '&#x2615;'; ...
        'Coffee Machine',     '&#x2615;'; ...
        'espresso maker',     '&#x2615;'; ...
        'Salt Shaker',        '&#x1F9C2;'; ...
        'saltshaker',         '&#x1F9C2;'; ...
        'measuring cup',      '&#x1F944;'; ...
        'wooden spoon',       '&#x1F944;'; ...
        ... % === Tech & electronics ===
        'umbrella',           '&#x2602;'; ...
        'Flashlight',         '&#x1F526;'; ...
        'flashlight',         '&#x1F526;'; ...
        'torch',              '&#x1F526;'; ...
        'Remote',             '&#x1F4FA;'; ...
        'remote control',     '&#x1F4FA;'; ...
        'Phone',              '&#x1F4F1;'; ...
        'cellular telephone', '&#x1F4F1;'; ...
        'Old Phone',          '&#x1F4DE;'; ...
        'dial telephone',     '&#x1F4DE;'; ...
        'Pay Phone',          '&#x1F4DE;'; ...
        'pay-phone',          '&#x1F4DE;'; ...
        'digital clock',      '&#x1F550;'; ...
        'analog clock',       '&#x1F550;'; ...
        'wall clock',         '&#x1F550;'; ...
        'alarm clock',        '&#x23F0;'; ...
        'digital watch',      '&#x231A;'; ...
        'stopwatch',          '&#x23F1;'; ...
        'hourglass',          '&#x231B;'; ...
        'Keyboard',           '&#x2328;'; ...
        'keyboard',           '&#x2328;'; ...
        'computer keyboard',  '&#x2328;'; ...
        'Typewriter',         '&#x2328;'; ...
        'typewriter keyboard','&#x2328;'; ...
        'Computer Mouse',     '&#x1F5B1;'; ...
        'mouse',              '&#x1F5B1;'; ...
        'Monitor',            '&#x1F5A5;'; ...
        'monitor',            '&#x1F5A5;'; ...
        'Computer',           '&#x1F5A5;'; ...
        'desktop computer',   '&#x1F5A5;'; ...
        'TV',                 '&#x1F4FA;'; ...
        'television',         '&#x1F4FA;'; ...
        'screen',             '&#x1F4FA;'; ...
        'Music Player',       '&#x1F3B5;'; ...
        'iPod',               '&#x1F3B5;'; ...
        'headphone',          '&#x1F3A7;'; ...
        'Radio',              '&#x1F4FB;'; ...
        'radio',              '&#x1F4FB;'; ...
        'Camera',             '&#x1F4F7;'; ...
        'reflex camera',      '&#x1F4F7;'; ...
        'Instant Camera',     '&#x1F4F7;'; ...
        'Polaroid camera',    '&#x1F4F7;'; ...
        'Projector',          '&#x1F4FD;'; ...
        'projector',          '&#x1F4FD;'; ...
        'Speaker',            '&#x1F50A;'; ...
        'loudspeaker',        '&#x1F50A;'; ...
        'microphone',         '&#x1F3A4;'; ...
        'Copier',             '&#x1F5A8;'; ...
        'photocopier',        '&#x1F5A8;'; ...
        'printer',            '&#x1F5A8;'; ...
        ... % === Tools ===
        'hammer',             '&#x1F528;'; ...
        'screwdriver',        '&#x1FA9B;'; ...
        'wrench',             '&#x1F527;'; ...
        'power drill',        '&#x1F527;'; ...
        'Axe',                '&#x1FA93;'; ...
        'hatchet',            '&#x1FA93;'; ...
        'Chainsaw',           '&#x1FA9A;'; ...
        'chain saw',          '&#x1FA9A;'; ...
        'Toolbox',            '&#x1F9F0;'; ...
        'carpenter''s kit',   '&#x1F9F0;'; ...
        'paintbrush',         '&#x1F58C;'; ...
        'shovel',             '&#x26CF;'; ...
        'bucket',             '&#x1FAA3;'; ...
        'Wheelbarrow',        '&#x1F6D2;'; ...
        'barrow',             '&#x1F6D2;'; ...
        'lawnmower',          '&#x1F33F;'; ...
        'lawn mower',         '&#x1F33F;'; ...
        'broom',              '&#x1F9F9;'; ...
        'plunger',            '&#x1FAA0;'; ...
        ... % === Vehicles ===
        'bicycle',            '&#x1F6B2;'; ...
        'mountain bike',      '&#x1F6B2;'; ...
        'tricycle',           '&#x1F6B2;'; ...
        'unicycle',           '&#x1F6B2;'; ...
        'scooter',            '&#x1F6F4;'; ...
        'Scooter',            '&#x1F6F4;'; ...
        'motor scooter',      '&#x1F6F4;'; ...
        'moped',              '&#x1F6F4;'; ...
        'skateboard',         '&#x1F6F9;'; ...
        'car',                '&#x1F697;'; ...
        'Car',                '&#x1F697;'; ...
        'sports car',         '&#x1F697;'; ...
        'convertible',        '&#x1F697;'; ...
        'Race Car',           '&#x1F3CE;'; ...
        'racer',              '&#x1F3CE;'; ...
        'Go-Kart',            '&#x1F3CE;'; ...
        'go-kart',            '&#x1F3CE;'; ...
        'Golf Cart',          '&#x1F3CE;'; ...
        'golfcart',           '&#x1F3CE;'; ...
        'jeep',               '&#x1F699;'; ...
        'Pickup Truck',       '&#x1F6FB;'; ...
        'pickup',             '&#x1F6FB;'; ...
        'Semi Truck',         '&#x1F69B;'; ...
        'trailer truck',      '&#x1F69B;'; ...
        'truck',              '&#x1F69A;'; ...
        'Moving Truck',       '&#x1F69A;'; ...
        'moving van',         '&#x1F69A;'; ...
        'Garbage Truck',      '&#x1F69A;'; ...
        'garbage truck',      '&#x1F69A;'; ...
        'Tow Truck',          '&#x1F69A;'; ...
        'tow truck',          '&#x1F69A;'; ...
        'Taxi',               '&#x1F695;'; ...
        'cab',                '&#x1F695;'; ...
        'school bus',         '&#x1F68C;'; ...
        'Bus',                '&#x1F68C;'; ...
        'minibus',            '&#x1F68C;'; ...
        'trolleybus',         '&#x1F68C;'; ...
        'fire engine',        '&#x1F692;'; ...
        'ambulance',          '&#x1F691;'; ...
        'police van',         '&#x1F694;'; ...
        'Train',              '&#x1F682;'; ...
        'bullet train',       '&#x1F685;'; ...
        'electric locomotive','&#x1F682;'; ...
        'steam locomotive',   '&#x1F682;'; ...
        'Train Car',          '&#x1F683;'; ...
        'freight car',        '&#x1F683;'; ...
        'passenger car',      '&#x1F683;'; ...
        'Trolley',            '&#x1F68B;'; ...
        'streetcar',          '&#x1F68B;'; ...
        'Ship',               '&#x1F6A2;'; ...
        'container ship',     '&#x1F6A2;'; ...
        'Cruise Ship',        '&#x1F6F3;'; ...
        'liner',              '&#x1F6F3;'; ...
        'Boat',               '&#x26F5;'; ...
        'catamaran',          '&#x26F5;'; ...
        'gondola',            '&#x26F5;'; ...
        'Sailboat',           '&#x26F5;'; ...
        'schooner',           '&#x26F5;'; ...
        'yawl',               '&#x26F5;'; ...
        'canoe',              '&#x1F6F6;'; ...
        'Speedboat',          '&#x1F6A4;'; ...
        'speedboat',          '&#x1F6A4;'; ...
        'lifeboat',           '&#x26F5;'; ...
        'airplane',           '&#x2708;'; ...
        'Airplane',           '&#x2708;'; ...
        'airliner',           '&#x2708;'; ...
        'Blimp',              '&#x1F6E9;'; ...
        'airship',            '&#x1F6E9;'; ...
        'helicopter',         '&#x1F681;'; ...
        'rocket',             '&#x1F680;'; ...
        'space shuttle',      '&#x1F680;'; ...
        'parachute',          '&#x1FA82;'; ...
        'tractor',            '&#x1F69C;'; ...
        ... % === Toys & fun ===
        'teddy',              '&#x1F9F8;'; ...
        'teddy bear',         '&#x1F9F8;'; ...
        'balloon',            '&#x1F388;'; ...
        'confetti',           '&#x1F389;'; ...
        'pinwheel',           '&#x1FA81;'; ...
        'kite',               '&#x1FA81;'; ...
        'toy',                '&#x1F9F8;'; ...
        'toyshop',            '&#x1F9F8;'; ...
        'jigsaw puzzle',      '&#x1F9E9;'; ...
        'Rubik''s cube',      '&#x1F7E5;'; ...
        'Lego',               '&#x1F9F1;'; ...
        'abacus',             '&#x1F9EE;'; ...
        'top',                '&#x1FA80;'; ...
        'Jack-o-Lantern',     '&#x1F383;'; ...
        'jack-o''-lantern',   '&#x1F383;'; ...
        'Christmas stocking', '&#x1F9E6;'; ...
        'Merry-Go-Round',     '&#x1F3A0;'; ...
        'carousel',           '&#x1F3A0;'; ...
        'Slot Machine',       '&#x1F3B0;'; ...
        'slot',               '&#x1F3B0;'; ...
        ... % === Nature & scenery ===
        'daisy',              '&#x1F33C;'; ...
        'sunflower',          '&#x1F33B;'; ...
        'rose',               '&#x1F339;'; ...
        'Orchid',             '&#x1F33A;'; ...
        'Flower Field',       '&#x1F33B;'; ...
        'rapeseed',           '&#x1F33B;'; ...
        'volcano',            '&#x1F30B;'; ...
        'Mountain',           '&#x1F3D4;'; ...
        'alp',                '&#x1F3D4;'; ...
        'Beach',              '&#x1F3D6;'; ...
        'seashore',           '&#x1F3D6;'; ...
        'sandbar',            '&#x1F3D6;'; ...
        'coral reef',         '&#x1FAB8;'; ...
        'valley',             '&#x1F3DE;'; ...
        ... % === Landmarks & buildings ===
        'mask',               '&#x1F3AD;'; ...
        'globe',              '&#x1F30D;'; ...
        'Compass',            '&#x1F9ED;'; ...
        'compass',            '&#x1F9ED;'; ...
        'magnetic compass',   '&#x1F9ED;'; ...
        'Magnifying Glass',   '&#x1F50D;'; ...
        'magnifying glass',   '&#x1F50D;'; ...
        'loupe',              '&#x1F50D;'; ...
        'binoculars',         '&#x1F52D;'; ...
        'telescope',          '&#x1F52D;'; ...
        'Telescope',          '&#x1F52D;'; ...
        'radio telescope',    '&#x1F52D;'; ...
        'candle',             '&#x1F56F;'; ...
        'lantern',            '&#x1F3EE;'; ...
        'Lighthouse',         '&#x1F3E0;'; ...
        'lighthouse',         '&#x1F3E0;'; ...
        'beacon',             '&#x1F3E0;'; ...
        'church',             '&#x26EA;'; ...
        'castle',             '&#x1F3F0;'; ...
        'palace',             '&#x1F3F0;'; ...
        'fountain',           '&#x26F2;'; ...
        'Bridge',             '&#x1F309;'; ...
        'bridge',             '&#x1F309;'; ...
        'steel arch bridge',  '&#x1F309;'; ...
        'suspension bridge',  '&#x1F309;'; ...
        'dam',                '&#x1F30A;'; ...
        'Arch',               '&#x1F3DB;'; ...
        'triumphal arch',     '&#x1F3DB;'; ...
        'Monument',           '&#x1F3DB;'; ...
        'obelisk',            '&#x1F3DB;'; ...
        'Bell Tower',         '&#x1F514;'; ...
        'bell cote',          '&#x1F514;'; ...
        'dome',               '&#x1F3DB;'; ...
        'barn',               '&#x1F3D5;'; ...
        'Tent',               '&#x26FA;'; ...
        'mountain tent',      '&#x26FA;'; ...
        ... % === Misc objects ===
        'traffic light',      '&#x1F6A6;'; ...
        'stop sign',          '&#x1F6D1;'; ...
        'mailbox',            '&#x1F4EE;'; ...
        'parking meter',      '&#x1F17F;'; ...
        'Bench',              '&#x1FA91;'; ...
        'bench',              '&#x1FA91;'; ...
        'park bench',         '&#x1FA91;'; ...
        'Lock',               '&#x1F512;'; ...
        'padlock',            '&#x1F512;'; ...
        'combination lock',   '&#x1F512;'; ...
        'Match',              '&#x1F9E8;'; ...
        'matchstick',         '&#x1F9E8;'; ...
        'safe',               '&#x1F510;'; ...
        'Fence',              '&#x1F3E0;'; ...
        'picket fence',       '&#x1F3E0;'; ...
        'chainlink fence',    '&#x1F3E0;'; ...
        'Satellite Dish',     '&#x1F4E1;'; ...
        'solar dish',         '&#x1F4E1;'; ...
        'flagpole',           '&#x1F3F3;'; ...
        'stethoscope',        '&#x1FA7A;'; ...
        'syringe',            '&#x1F489;'; ...
        'pill bottle',        '&#x1F48A;'; ...
        'Band Aid',           '&#x1FA79;'; ...
        'dumbbell',           '&#x1F4AA;'; ...
        'barbell',            '&#x1F4AA;'; ...
        'punching bag',       '&#x1F94A;'; ...
        'shield',             '&#x1F6E1;'; ...
        'Spiderweb',          '&#x1F578;'; ...
        'spider web',         '&#x1F578;'; ...
        'honeycomb',          '&#x1F36F;'; ...
        'ATM',                '&#x1F3E7;'; ...
        'cash machine',       '&#x1F3E7;'; ...
        'vending machine',    '&#x1F3E7;'; ...
        'piggy bank',         '&#x1F911;'; ...
        'Sink',               '&#x1F6B0;'; ...
        'washbasin',          '&#x1F6B0;'; ...
        'Toilet',             '&#x1F6BD;'; ...
        'toilet seat',        '&#x1F6BD;'; ...
        'Toilet Paper',       '&#x1F9FB;'; ...
        'toilet tissue',      '&#x1F9FB;'; ...
        'Bathtub',            '&#x1F6C1;'; ...
        'bathtub',            '&#x1F6C1;'; ...
        'pillow',             '&#x1F4A4;'; ...
        'quilt',              '&#x1F4A4;'; ...
        'sleeping bag',       '&#x1F4A4;'; ...
        'Bed',                '&#x1F6CF;'; ...
        'four-poster',        '&#x1F6CF;'; ...
        'Couch',              '&#x1F6CB;'; ...
        'studio couch',       '&#x1F6CB;'; ...
        'Fridge',             '&#x1F9CA;'; ...
        'refrigerator',       '&#x1F9CA;'; ...
        'toaster',            '&#x1F35E;'; ...
        'stove',              '&#x1F373;'; ...
        'microwave',          '&#x1F373;'; ...
        'Washing Machine',    '&#x1F9FA;'; ...
        'washer',             '&#x1F9FA;'; ...
        'vacuum',             '&#x1F9F9;'; ...
        'iron',               '&#x1F455;'; ...
        'Hair Dryer',         '&#x1F4A8;'; ...
        'hand blower',        '&#x1F4A8;'; ...
        'sewing machine',     '&#x1F9F5;'; ...
        'Rickshaw',           '&#x1F6D2;'; ...
        'jinrikisha',         '&#x1F6D2;'; ...
        'Dog Sled',           '&#x1F6D2;'; ...
        'dogsled',            '&#x1F6D2;'; ...
        'Cart',               '&#x1F6D2;'; ...
        'oxcart',             '&#x1F6D2;'; ...
        'Horse Cart',         '&#x1F6D2;'; ...
        'horse cart',         '&#x1F6D2;'; ...
        'snowmobile',         '&#x1F3CE;'; ...
        'submarine',          '&#x1F6A2;'; ...
    };

    emojiMap = containers.Map(lower(entries(:,1)), entries(:,2));
    cachedMap = emojiMap;
end
